remote_theme: jekyll-theme-clean-blog
title: Aquion Blog
description: Wichtige Lebenserkenntnisse mit Aquion
author: Tobias KÃ¶lpin
email: t.koelpin(at)web.de
tiktok_username: t.koelpin
github_username: tkoelpin
paginate: 5
paginate_path: "/blog/page:num/"